openapi: 3.0.0
info:
  title: MayurSocial
  description: Documentation learning app-1
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: Optional server description, e.g. Main (production) server
  - url: https://localhost:4000/api/v1
    description: Dummy url it doesn't work

components:
  securitySchemes:

    BasicAuth:
      type: http
      scheme: basic
  
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary: returns username, followers and follows 
      responses:
        '200': # status code
          description: returns an object 
          content:
            application/json:
              schema:
                type: object
                properties: 
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string
                  date: 
                    type: string

  /{token}:
    get:
      summary: returns whatever is there in parameters 
      parameters:
        - name: token
          default: 5
          in: path
          schema:
            type: string
      responses:
        '200': # status code
          description: returns an object 
          content:
            application/json:
              schema:
                type: object
                properties: 
                  params:
                    type: string
  
